### ISSUE TITLE
issuer cannot be empty

### ISSUE THREAD

**Issue by finelycheng** [okta/samples-java-spring#15]
when i boot the application  with the args 

mvn -Dokta.oauth2.issuer=https://dev-123456.oktapreview.com/oauth2/default \
    -Dokta.oauth2.clientId=YourClientId \
    -Dokta.oauth2.clientSecret=YourClientSecret

this happend
java.lang.IllegalArgumentException: issuer cannot be empty
	at org.springframework.util.Assert.hasText(Assert.java:181)
	at com.okta.spring.oauth.discovery.OidcDiscoveryClient.<init>(OidcDiscoveryClient.java:36)
	at com.okta.spring.oauth.OktaPropertiesMappingEnvironmentPostProcessor.discoveryPropertiesSource(OktaPropertiesMappingEnvironmentPostProcessor.java:137)
	at com.okta.spring.oauth.OktaPropertiesMappingEnvironmentPostProcessor.postProcessEnvironment(OktaPropertiesMappingEnvironmentPostProcessor.java:95)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:182)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:168)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:296)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)

**Comment by bdemers** [comment]
Hey @finelycheng sorry for not seeing this earlier! (no excuse really)

There was a similar parsing error in an earlier version (resolved now), if you want to give it another shot let us know how it goes!
