### ISSUE TITLE
Startup error in okta-hosted-login project

### ISSUE THREAD

**Issue by Carson-Keep-Running** [okta/samples-java-spring#159]
When I run the main() method in com.okta.spring.example.CodeFlowExampleApplication class, to startup the spring boot project using IntelliJ IDEA, the following error is occurred:
> Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://dev-xxxxxxxx.okta.com/oauth2/default/.well-known/openid-configuration": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:670) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:155) ~[spring-security-oauth2-client-5.7.4.jar:5.7.4]
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:208) ~[spring-security-oauth2-client-5.7.4.jar:5.7.4]
	... 122 common frames omitted

I have configured following environment variables: OKTA_OAUTH2_ISSUER, OKTA_OAUTH2_CLIENT_ID,  OKTA_OAUTH2_CLIENT_SECRET.
It seems need a certification to call the OKTA Oauth2 issuer URL, how can I get the OKTA cert and then I can import into the my JDK keystore?

**Comment by arvindkrishnakumar-okta** [comment]
Can you check if https://devforum.okta.com/t/spring-boot-application-failed-to-start-with-custom-url/13958 helps?

**Comment by arvindkrishnakumar-okta** [comment]
Closing this due to inactivity, feel free to reopen if further assistance is needed.
